apiVersion: food.training.sap/v1alpha1
kind: SteakfulSet
metadata:
  name: team-barbecue
spec:
  guests: 2
  steak:
    spec:
      cookLevel: medium
      fat: lean
      weight: 250
      variant: angus-rump
