# Prior to using this manifest, ensure that the image is avaible in the registry
# To do so, run
# docker pull --platform linux/amd64 nginx:latest
# docker tag nginx:latest h.ingress.<cluster-name>.<project-name>.shoot.canary.k8s-hana.ondemand.com/training/nginx:latest
# docker push h.ingress.<cluster-name>.<project-name>.shoot.canary.k8s-hana.ondemand.com/training/nginx:latest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-image-secret
  labels:
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: h.ingress.ingress.<cluster-name>.<project-name>.shoot.canary.k8s-hana.ondemand.com/training/nginx:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: myimagesecret
