# File: 05-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: i310202
type: Opaque
stringData:                  # stringData auto-encodes to base64
  DB_USER: fortuneuser
  DB_PASSWORD: supersecret123