# File: 07-postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: i310202
type: Opaque
stringData:
  POSTGRES_DB: fortunedb
  POSTGRES_USER: fortuneuser
  POSTGRES_PASSWORD: fortunepass123