apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: echo-server
