---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fortune-cookies
  labels:
    component: ads
    module: app
  annotations:
    cert.gardener.cloud/purpose: managed
spec:
  rules:
  - host: app.etienne.ingress.yul38.k8s-train.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fortune-cookies
            port:
              name: http
  tls:
    - hosts:
      - app.etienne.ingress.yul38.k8s-train.shoot.canary.k8s-hana.ondemand.com
      secretName: fortune-cookies-tls-secret
