apiVersion: v1
kind: Secret
metadata:
  name: training-registry
stringData:
  .dockerconfigjson: '{"auths":{"h.ingress.<cluster-name>.<project-name>.shoot.canary.k8s-hana.ondemand.com":{"username":"participant","password":"2r4!rX6u5-qH","auth":"cGFydGljaXBhbnQ6MnI0IXJYNnU1LXFI"}}}'
type: kubernetes.io/dockerconfigjson
