---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-reviews-app-access
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.app" . | indent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "labels.reviews.app" . | indent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
      namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
    - podSelector:
        matchLabels:
          component: ads
  egress:
  - to:
    - podSelector:
        matchLabels: {{- include "labels.reviews.db" . | indent 10}}
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
      namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
    ports:
    - port: 8053
      protocol: UDP
    - port: 8053
      protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: node-local-dns
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP